### ISSUE TITLE
How to restore?

### ISSUE THREAD

**Issue by maartendamen** [piscue/docker-backup-scripts#6]
A back-up is as good as it's restore. So I wanted to restore, do you have some instructions on that?

**Comment by piscue** [comment]
the backups you have are docker backups. you should uncompress and check a docker save/restore reference. Sorry I didn't implement the restore part on this scripts

**Comment by maartendamen** [comment]
Thanks for the prompt response. I just recreated the images using docker compose. I was wondering about the volume restore, any hints?

**Comment by piscue** [comment]
if you look for docker volume restore you'll find the reference

**Comment by fwandson** [comment]
Muito obrigado!!!
