### ISSUE TITLE
":/backup not absolute: unknown"

### ISSUE THREAD

**Issue by Dandyliar** [piscue/docker-backup-scripts#8]
When i run the script I get this error 
`ghost - docker: Error response from daemon: OCI runtime create failed: invalid mount {Destination::/backup Type:bind Source:/var/lib/docker/volumes/$volume_ID/_data Options:[rbind]}: mount destination :/backup not absolute: unknown.
OK` This happens for all of my containers and I am running it as root.
Im kinda new to linux and I could just be messing something up but what am I doing wrong here?

Cheers

**Comment by piscue** [comment]
Maybe something change on docker over time, I'm not using this script anymore

you can try to tweak this line: https://github.com/piscue/docker-backup-scripts/blob/aa76dc430d5f5592b1fc06c872a318213341f729/backup-volumes.sh#L7
